# Generated by Django 2.2.11 on 2023-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', models.CharField(max_length=50, verbose_name='单词')),
                ('chinese', models.CharField(max_length=50, verbose_name='中文释义')),
                ('sentence', models.CharField(max_length=100, verbose_name='例句')),
                ('chinese_sentence', models.CharField(max_length=100, verbose_name='例句翻译')),
                ('type', models.CharField(max_length=100, verbose_name='被哪些单词书包含')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50, verbose_name='单词书名称')),
                ('code', models.CharField(max_length=1, verbose_name='单词书对应代码')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vocabularybooks',
            constraint=models.UniqueConstraint(fields=('code',), name='code'),
        ),
        migrations.AddConstraint(
            model_name='vocabulary',
            constraint=models.UniqueConstraint(fields=('vocabulary',), name='vocabulary'),
        ),
    ]
