# Generated by Django 4.1.7 on 2023-06-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='word',
            name='word',
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('word', 'language', 'book'), name='book_word'),
        ),
    ]
