# Generated by Django 2.2.11 on 2023-05-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50, verbose_name='单词书名称')),
                ('code', models.CharField(max_length=1, verbose_name='单词书对应代码')),
            ],
        ),
        migrations.DeleteModel(
            name='VocabularyBooks',
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='vocabularybook',
            constraint=models.UniqueConstraint(fields=('code',), name='code'),
        ),
    ]
