# Generated by Django 2.2.11 on 2023-05-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0002_auto_20230530_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalVocabularyBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(max_length=20, verbose_name='账号')),
                ('vocabulary', models.CharField(max_length=50, verbose_name='单词')),
                ('first_met_date', models.DateField(auto_now_add=True)),
                ('last_met_date', models.DateField(auto_now=True)),
                ('is_remembered', models.BooleanField()),
            ],
        ),
    ]
