# Generated by Django 2.2.11 on 2023-05-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0003_personalvocabularybook'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vocabularybook',
            constraint=models.UniqueConstraint(fields=('book_name',), name='book_name'),
        ),
    ]
