# Generated by Django 2.2.11 on 2023-05-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0004_auto_20230530_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalvocabularybook',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
