# Generated by Django 2.2.11 on 2023-05-31 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0005_personalvocabularybook_is_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalvocabularybook',
            old_name='is_started',
            new_name='is_staring',
        ),
    ]
